name: Build AWS

on:
  push:
    branches: [ production ]
  pull_request:
    branches: [ production ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      uses: actions/checkout@v2

      name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2

      with:
        node-version: ${{ matrix.node-version }}

      name: Install Dependencies
      run: npm install

      name: Build Angular Application
      run: npm run build

      name: Deploy to S3 and Cloudfront
      uses: reggionick/s3-deploy@v3
      with:
        folder: dist
        bucket: ${{ secrets.AWS_AAM_BUCKET_NAME }}
        bucket-region: ${{ secrets.AWS_REGION }}
        dist-id: ${{ secrets.CLOUDFRONT_GGB_DISTRIBUTION }}
        invalidation: /
        delete-removed: true
        no-cache: true
        private: true

